const axios = require('axios');

module.exports = {
    cmd: "fb",
    alias: ["facebook", "fbdl"],
    desc: "Download Facebook videos",
    category: "DOWNLOAD",
    async execute(conn, m, { args }) {
        const text = args.join(" ");
        if (!text) return m.reply("Please provide a Facebook video URL!");

        await m.react("⏳");

        try {
            // Using a standard API endpoint structure for the provided JSON
            const apiurl = `https://api.qasim-ali.com/api/fbdl?url=${encodeURIComponent(text)}`;
            const response = await axios.get(apiurl);
            const data = response.data;

            if (!data.status || !data.result) {
                await m.react("❌");
                return m.reply("Failed to fetch video. Make sure the link is valid and public.");
            }

            const video = data.result.media;
            const videoUrl = video.video_url_hd || video.video_url_sd;
            const caption = `*ᴘᴏᴘᴋɪᴅ ғʙ ᴅᴏᴡɴʟᴏᴀᴅᴇʀ* 🚀\n\n` +
                            `*📌 Title:* ${video.title}\n` +
                            `*🔗 Source:* ${video.platform}\n\n` +
                            `*Generated by Popkid AI*`;

            await conn.sendMessage(m.chat, { 
                video: { url: videoUrl }, 
                caption: caption 
            }, { quoted: m });

            await m.react("✅");

        } catch (e) {
            console.error(e);
            await m.react("❌");
            m.reply("An error occurred. The API might be down or the link is private.");
        }
    }
};
